import java.awt.Toolkit;
import java.awt.datatransfer.StringSelection;
import java.awt.event.KeyEvent;
import java.util.Random;

import javax.swing.JOptionPane;

import org.jdesktop.swingx.prompt.PromptSupport;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author YATRAONLINE\deepak.singh2
 */
public class Main extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4162544929768886265L;

	/**
	 * Creates new form MainFrame
	 */
	public Main() {
		initComponents();
		setLocationRelativeTo(this);
		setResizable(false);
		setTitle("Random Number Generator");
		PromptSupport.setPrompt("Current Number", currentTextField);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		currentTextField = new javax.swing.JTextField();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		currentTextField.setFont(new java.awt.Font("Ubuntu", 2, 16)); // NOI18N
		currentTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		currentTextField.setToolTipText("Enter Current Number");
		currentTextField.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyReleased(java.awt.event.KeyEvent evt) {
				currentTextFieldKeyReleased(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(currentTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(currentTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE));

		pack();
	}// </editor-fold>

	private void currentTextFieldKeyReleased(java.awt.event.KeyEvent event) {
		String currentText = currentTextField.getText().trim();
		if (currentText.equals("")) {
			JOptionPane.showMessageDialog(this, "Please enter a valid numerical value");
		} else {
			if (event.getKeyCode() == KeyEvent.VK_ENTER) {
				String randomText = getRandom(currentText);
				if (randomText.equals("")) {
					JOptionPane.showMessageDialog(this, "Please enter a valid numerical value");
					currentTextField.setText("");
				} else {
					Toolkit.getDefaultToolkit().getSystemClipboard().setContents(new StringSelection(randomText), null);
					JOptionPane.showMessageDialog(this,
							"<html>Random number is <b>" + randomText + "</b> & copied to clipboard</html>");
				}
			}
		}
	}

	private String getRandom(String currentText) {
		try {
			return String.valueOf(new Random().nextInt(5003) + Long.parseLong(currentText) + 1009);
		} catch (Exception e) {
			return "";
		}
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Main().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JTextField currentTextField;
	// End of variables declaration
}
